In [4]:
%pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [5]:
import yfinance as yf
import pandas as pd
import os
import time

""" os.makedirs('stock_data', exist_ok=True)

tickers_df = pd.read_csv('nse.csv')
tikers = tickers_df['SYMBOL'].tolist()

start_date = '2020-01-01'
end_date = '2024-12-01'

for ticker in tikers:
    full_ticker = f"{ticker}.NS"
    print(f"Downloading data for {full_ticker}...")
    try:
        data = yf.download(full_ticker, start=start_date, end=end_date)
        if not data.empty:
            data.to_csv(f'stock_data/{ticker}.csv')
            print(f"Data for {full_ticker} saved successfully.")
        else:
            print(f"No data found for {full_ticker}.")
    except Exception as e:
        print(f"Error downloading {full_ticker}: {e}")
    time.sleep(1)  # Be respectful to the API rate limits """

' os.makedirs(\'stock_data\', exist_ok=True)\n\ntickers_df = pd.read_csv(\'nse.csv\')\ntikers = tickers_df[\'SYMBOL\'].tolist()\n\nstart_date = \'2020-01-01\'\nend_date = \'2024-12-01\'\n\nfor ticker in tikers:\n    full_ticker = f"{ticker}.NS"\n    print(f"Downloading data for {full_ticker}...")\n    try:\n        data = yf.download(full_ticker, start=start_date, end=end_date)\n        if not data.empty:\n            data.to_csv(f\'stock_data/{ticker}.csv\')\n            print(f"Data for {full_ticker} saved successfully.")\n        else:\n            print(f"No data found for {full_ticker}.")\n    except Exception as e:\n        print(f"Error downloading {full_ticker}: {e}")\n    time.sleep(1)  # Be respectful to the API rate limits '

Fetch History Of Stock Data

In [6]:
def fetch_history_stock_data(ticker, start_date='2020-01-01', end_date='2024-12-01'):
    full_ticker = f"{ticker}.NS"
    print(f"Downloading data for {full_ticker}...")
    try:
        data = yf.download(full_ticker, start=start_date, end=end_date)
        if not data.empty:
            return data
        else:
            print(f"No data found for {full_ticker}.")
            return None
    except Exception as e:
        print(f"Error downloading {full_ticker}: {e}")
        return None

fetch_history_stock_data('RELIANCE')

YF.download() has changed argument auto_adjust default to True


[*********************100%***********************]  1 of 1 completed


Price             Close         High          Low         Open      Volume
Ticker      RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS RELIANCE.NS
Date                                                                      
2020-01-01   690.138306   698.138733   688.263977   693.978516    14004468
2020-01-02   701.887512   704.470520   691.235535   691.235535    17710316
2020-01-03   702.733276   704.790527   696.264343   700.835999    20984698
2020-01-06   686.435303   698.504456   684.835205   694.892883    24519177
2020-01-07   696.995850   701.521790   691.921265   694.435669    16683622
...                 ...          ...          ...          ...         ...
2024-11-25  1287.000000  1304.449951  1282.449951  1290.000000    28923341
2024-11-26  1295.699951  1297.849976  1284.199951  1294.949951     9247557
2024-11-27  1293.199951  1303.849976  1286.000000  1293.500000     9572746
2024-11-28  1270.800049  1296.599976  1269.050049  1289.949951    15027412
2024-11-29  1292.199951  1299.500000  1275.250000  1280.000000    13202307

[1217 rows x 5 columns]

Fetch 15Min Stock Data


In [7]:
def fetch_fifteenmin_stock_data(ticker,period='1d',interval='15m'):
    full_ticker = f"{ticker}.NS"
    print(f"Downloading intraday data for {full_ticker}...")
    try:
        data = yf.download(full_ticker, period=period, interval=interval)
        if not data.empty:
            return data
        else:
            print(f"No intraday data found for {full_ticker}.")
            return None
    except Exception as e:
        print(f"Error downloading intraday data for {full_ticker}: {e}")
        return None

fetch_fifteenmin_stock_data('RELIANCE')

[*********************100%***********************]  1 of 1 completed


Price                            Close         High          Low         Open  \
Ticker                     RELIANCE.NS  RELIANCE.NS  RELIANCE.NS  RELIANCE.NS   
Datetime                                                                        
2025-06-04 03:45:00+00:00  1407.500000  1414.599976  1406.099976  1414.599976   
2025-06-04 04:00:00+00:00  1407.199951  1409.500000  1406.199951  1408.000000   
2025-06-04 04:15:00+00:00  1408.800049  1409.699951  1406.199951  1407.400024   
2025-06-04 04:30:00+00:00  1408.000000  1410.599976  1407.000000  1409.000000   
2025-06-04 04:45:00+00:00  1409.400024  1411.099976  1408.000000  1408.199951   
2025-06-04 05:00:00+00:00  1408.599976  1410.000000  1407.699951  1409.099976   
2025-06-04 05:15:00+00:00  1409.300049  1409.300049  1407.500000  1408.699951   
2025-06-04 05:30:00+00:00  1408.000000  1409.500000  1407.800049  1409.199951   
2025-06-04 05:45:00+00:00  1409.400024  1411.500000  1407.199951  1408.000000   
2025-06-04 06:00:00+00:00  1410.599976  1411.000000  1409.000000  1409.599976   
2025-06-04 06:15:00+00:00  1413.500000  1413.699951  1410.599976  1410.900024   
2025-06-04 06:30:00+00:00  1413.099976  1413.900024  1411.300049  1413.500000   
2025-06-04 06:45:00+00:00  1410.400024  1413.699951  1410.000000  1413.000000   
2025-06-04 07:00:00+00:00  1412.199951  1412.300049  1409.900024  1410.400024   
2025-06-04 07:15:00+00:00  1413.500000  1413.800049  1412.099976  1412.099976   
2025-06-04 07:30:00+00:00  1415.099976  1415.800049  1413.599976  1413.599976   
2025-06-04 07:45:00+00:00  1415.400024  1415.800049  1413.800049  1415.099976   
2025-06-04 08:00:00+00:00  1416.400024  1416.699951  1414.599976  1415.500000   
2025-06-04 08:15:00+00:00  1418.699951  1418.900024  1415.599976  1416.400024   
2025-06-04 08:30:00+00:00  1418.400024  1419.599976  1415.800049  1418.800049   
2025-06-04 08:45:00+00:00  1419.300049  1420.699951  1418.000000  1418.400024   
2025-06-04 09:00:00+00:00  1420.000000  1420.699951  1418.500000  1419.300049   
2025-06-04 09:15:00+00:00  1422.000000  1422.599976  1419.900024  1420.099976   
2025-06-04 09:30:00+00:00  1424.000000  1425.599976  1422.000000  1422.099976   
2025-06-04 09:45:00+00:00  1421.000000  1424.300049  1420.099976  1423.900024   

Price                          Volume  
Ticker                    RELIANCE.NS  
Datetime                               
2025-06-04 03:45:00+00:00      395442  
2025-06-04 04:00:00+00:00      234735  
2025-06-04 04:15:00+00:00      129638  
2025-06-04 04:30:00+00:00     1216288  
2025-06-04 04:45:00+00:00      140309  
2025-06-04 05:00:00+00:00       66975  
2025-06-04 05:15:00+00:00       64827  
2025-06-04 05:30:00+00:00       76189  
2025-06-04 05:45:00+00:00      441108  
2025-06-04 06:00:00+00:00      208600  
2025-06-04 06:15:00+00:00      112920  
2025-06-04 06:30:00+00:00       88659  
2025-06-04 06:45:00+00:00      184111  
2025-06-04 07:00:00+00:00       90805  
2025-06-04 07:15:00+00:00      109220  
2025-06-04 07:30:00+00:00      181324  
2025-06-04 07:45:00+00:00      113784  
2025-06-04 08:00:00+00:00       89326  
2025-06-04 08:15:00+00:00      128067  
2025-06-04 08:30:00+00:00      283901  
2025-06-04 08:45:00+00:00      358653  
2025-06-04 09:00:00+00:00      386698  
2025-06-04 09:15:00+00:00      553861  
2025-06-04 09:30:00+00:00     1292917  
2025-06-04 09:45:00+00:00      889630

In [8]:
def fix_multilevel_columns(df):
    """Flattens multi-index columns if present."""
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df.columns.values]
    return df

# fetch_history_stock_data('RELIANCE')
fix_multilevel_columns(fetch_history_stock_data('RELIANCE'))

[*********************100%***********************]  1 of 1 completed

Close_RELIANCE.NS  High_RELIANCE.NS  Low_RELIANCE.NS  \
Date                                                               
2020-01-01         690.138306        698.138733       688.263977   
2020-01-02         701.887512        704.470520       691.235535   
2020-01-03         702.733276        704.790527       696.264343   
2020-01-06         686.435303        698.504456       684.835205   
2020-01-07         696.995850        701.521790       691.921265   
...                       ...               ...              ...   
2024-11-25        1287.000000       1304.449951      1282.449951   
2024-11-26        1295.699951       1297.849976      1284.199951   
2024-11-27        1293.199951       1303.849976      1286.000000   
2024-11-28        1270.800049       1296.599976      1269.050049   
2024-11-29        1292.199951       1299.500000      1275.250000   

            Open_RELIANCE.NS  Volume_RELIANCE.NS  
Date                                              
2020-01-01        693.978516            14004468  
2020-01-02        691.235535            17710316  
2020-01-03        700.835999            20984698  
2020-01-06        694.892883            24519177  
2020-01-07        694.435669            16683622  
...                      ...                 ...  
2024-11-25       1290.000000            28923341  
2024-11-26       1294.949951             9247557  
2024-11-27       1293.500000             9572746  
2024-11-28       1289.949951            15027412  
2024-11-29       1280.000000            13202307  

[1217 rows x 5 columns]

Preprocessing and Cleaning

In [9]:
def clean_stock_data(df, ticker='UNKNOWN'):
    print("🧹 Cleaning stock data...")

    # Fix multilevel columns if needed
    df = fix_multilevel_columns(df)

    # Reset index and rename 'index' to 'Date' if necessary
    df.reset_index(inplace=True)
    if 'Date' not in df.columns:
        df.rename(columns={'index': 'Date'}, inplace=True)

    # Drop NaNs
    df.dropna(inplace=True)

    # Convert 'Date' to datetime
    df['Date'] = pd.to_datetime(df['Date'])
    df.sort_values(by='Date', inplace=True)

    # Ensure symbol column exists
    df['Symbol'] = ticker

    # Drop duplicates
    df.drop_duplicates(subset=['Date', 'Symbol'], inplace=True)

    # Remove unwanted columns
    drop_cols = [col for col in df.columns if 'Adj Close' in col]
    if drop_cols:
        df.drop(columns=drop_cols, inplace=True)

    # Rename prefixed columns to standard ones
    rename_cols = {
        f'Open_{ticker}.NS': 'Open',
        f'High_{ticker}.NS': 'High',
        f'Low_{ticker}.NS': 'Low',
        f'Close_{ticker}.NS': 'Close',
        f'Price_{ticker}.NS': 'Price',
        f'Volume_{ticker}.NS': 'Volume',
    }
    df.rename(columns=rename_cols, inplace=True)

    # Add feature engineering columns
    df['DayOfWeek'] = df['Date'].dt.dayofweek
    df['Month'] = df['Date'].dt.month
    df['Year'] = df['Date'].dt.year
    df['Daily Change'] = df['Close'] - df['Open']
    df['Price Change'] = df['High'] - df['Low']
    df['Volatility'] = (df['High'] - df['Low']) / df['Open']
    df['Price Change %'] = (df['Price Change'] / df['Open']) * 100
    df['Daily Change %'] = (df['Daily Change'] / df['Open']) * 100

    return df


In [10]:
raw_df = fetch_history_stock_data('RELIANCE')
cleaned_df = clean_stock_data(raw_df, ticker='RELIANCE')
print(cleaned_df.head())

[*********************100%***********************]  1 of 1 completed

🧹 Cleaning stock data...
        Date       Close        High         Low        Open    Volume  \
0 2020-01-01  690.138306  698.138733  688.263977  693.978516  14004468   
1 2020-01-02  701.887512  704.470520  691.235535  691.235535  17710316   
2 2020-01-03  702.733276  704.790527  696.264343  700.835999  20984698   
3 2020-01-06  686.435303  698.504456  684.835205  694.892883  24519177   
4 2020-01-07  696.995850  701.521790  691.921265  694.435669  16683622   

     Symbol  DayOfWeek  Month  Year  Daily Change  Price Change  Volatility  \
0  RELIANCE          2      1  2020     -3.840210      9.874756    0.014229   
1  RELIANCE          3      1  2020     10.651978     13.234985    0.019147   
2  RELIANCE          4      1  2020      1.897278      8.526184    0.012166   
3  RELIANCE          0      1  2020     -8.457581     13.669250    0.019671   
4  RELIANCE          1      1  2020      2.560181      9.600525    0.013825   

   Price Change %  Daily Change %  
0        1.422920  

Classfication Model Training

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [12]:
def add_technical_indicators(df):
    df['SMA_5'] = df['Close'].rolling(window=5).mean()
    df['SMA_10'] = df['Close'].rolling(window=10).mean()
    df['EMA_5'] = df['Close'].ewm(span=5, adjust=False).mean()
    df['EMA_10'] = df['Close'].ewm(span=10, adjust=False).mean()

    delta = df['Close'].diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=14).mean()
    avg_loss = loss.rolling(window=14).mean()
    rs = avg_gain / avg_loss
    df['RSI'] = 100 - (100 / (1 + rs))

    df.dropna(inplace=True)
    return df


In [13]:
df = fetch_history_stock_data('RELIANCE')
df = clean_stock_data(df, ticker='RELIANCE')
df = add_technical_indicators(df)

[*********************100%***********************]  1 of 1 completed

🧹 Cleaning stock data...


In [14]:
df.head()

Date       Close        High         Low        Open    Volume  \
14 2020-01-21  701.247498  706.710632  695.807190  698.824524  18922720   
15 2020-01-22  700.996033  707.122070  699.967407  705.864868  10322817   
16 2020-01-23  698.024475  704.927673  695.212891  702.436096  11247739   
17 2020-01-24  695.601501  702.367554  694.229980  698.093018  14628445   
18 2020-01-27  688.743958  696.927246  688.035339  692.561340  13387750   

      Symbol  DayOfWeek  Month  Year  Daily Change  Price Change  Volatility  \
14  RELIANCE          1      1  2020      2.422974     10.903442    0.015603   
15  RELIANCE          2      1  2020     -4.868835      7.154663    0.010136   
16  RELIANCE          3      1  2020     -4.411621      9.714783    0.013830   
17  RELIANCE          4      1  2020     -2.491516      8.137573    0.011657   
18  RELIANCE          0      1  2020     -3.817383      8.891907    0.012839   

    Price Change %  Daily Change %       SMA_5      SMA_10       EMA_5  \
14        1.560255        0.346721  704.859094  703.620178  704.208340   
15        1.013602       -0.689769  705.727710  704.543652  703.137571   
16        1.383013       -0.628046  704.717383  703.576746  701.433205   
17        1.165686       -0.356903  699.281677  702.383545  699.489304   
18        1.283916       -0.551198  696.922693  700.685168  695.907522   

        EMA_10        RSI  
14  702.873841  54.600547  
15  702.532421  49.591963  
16  701.712795  47.885885  
17  700.601650  54.701059  
18  698.445706  45.600764

In [15]:
def add_target_label(df):
    df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)
    df.dropna(inplace=True)
    return df


In [16]:
add_target_label(df)
df.head()

Date       Close        High         Low        Open    Volume  \
14 2020-01-21  701.247498  706.710632  695.807190  698.824524  18922720   
15 2020-01-22  700.996033  707.122070  699.967407  705.864868  10322817   
16 2020-01-23  698.024475  704.927673  695.212891  702.436096  11247739   
17 2020-01-24  695.601501  702.367554  694.229980  698.093018  14628445   
18 2020-01-27  688.743958  696.927246  688.035339  692.561340  13387750   

      Symbol  DayOfWeek  Month  Year  ...  Price Change  Volatility  \
14  RELIANCE          1      1  2020  ...     10.903442    0.015603   
15  RELIANCE          2      1  2020  ...      7.154663    0.010136   
16  RELIANCE          3      1  2020  ...      9.714783    0.013830   
17  RELIANCE          4      1  2020  ...      8.137573    0.011657   
18  RELIANCE          0      1  2020  ...      8.891907    0.012839   

    Price Change %  Daily Change %       SMA_5      SMA_10       EMA_5  \
14        1.560255        0.346721  704.859094  703.620178  704.208340   
15        1.013602       -0.689769  705.727710  704.543652  703.137571   
16        1.383013       -0.628046  704.717383  703.576746  701.433205   
17        1.165686       -0.356903  699.281677  702.383545  699.489304   
18        1.283916       -0.551198  696.922693  700.685168  695.907522   

        EMA_10        RSI  Target  
14  702.873841  54.600547       0  
15  702.532421  49.591963       0  
16  701.712795  47.885885       0  
17  700.601650  54.701059       0  
18  698.445706  45.600764       0  

[5 rows x 21 columns]

In [17]:
from sklearn.preprocessing import StandardScaler

def scale_features(df, features):
    scaler = StandardScaler()
    df[features] = scaler.fit_transform(df[features])
    return df


In [18]:
def train_classifiers(df):
    features = ['Open', 'High', 'Low', 'Close', 'Volume', 'SMA_5', 'SMA_10', 'EMA_5', 'EMA_10', 'RSI']
    
    df = scale_features(df, features)
    X = df[features]
    y = df['Target']

    X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False, test_size=0.2)

    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Random Forest": RandomForestClassifier(n_estimators=100),
        "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        "LightGBM": LGBMClassifier()
    }

    for name, model in models.items():
        print(f"\n🧠 Training: {name}")
        model.fit(X_train, y_train)
        preds = model.predict(X_test)

        acc = accuracy_score(y_test, preds)
        cm = confusion_matrix(y_test, preds)

        print(f"✅ Accuracy: {acc:.4f}")
        print("✅ Confusion Matrix:\n", cm)
        print("✅ Classification Report:\n", classification_report(y_test, preds))


In [19]:
df = add_target_label(df)
train_classifiers(df)


🧠 Training: Logistic Regression
✅ Accuracy: 0.4730
✅ Confusion Matrix:
 [[85 28]
 [99 29]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.46      0.75      0.57       113
           1       0.51      0.23      0.31       128

    accuracy                           0.47       241
   macro avg       0.49      0.49      0.44       241
weighted avg       0.49      0.47      0.43       241


🧠 Training: Random Forest
✅ Accuracy: 0.4813
✅ Confusion Matrix:
 [[113   0]
 [125   3]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.47      1.00      0.64       113
           1       1.00      0.02      0.05       128

    accuracy                           0.48       241
   macro avg       0.74      0.51      0.34       241
weighted avg       0.75      0.48      0.33       241


🧠 Training: XGBoost
✅ Accuracy: 0.4772
✅ Confusion Matrix:
 [[109   4]
 [122   6]]
✅ Classification Report:
   

In [20]:
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands
from imblearn.over_sampling import SMOTE
import numpy as np

In [21]:
def add_tech_indicator(df):
    df['RSI'] = RSIIndicator(close=df['Close'], window=14).rsi()
    df['MACD'] = MACD(close=df['Close']).macd()
    bb = BollingerBands(close=df['Close'], window=20, window_dev=2)
    df['BB_High'] = bb.bollinger_hband()
    df['BB_Low'] = bb.bollinger_lband()

    df.dropna(inplace=True)
    return df

In [22]:
def preprocess(df):
    features = ['Open', 'High', 'Low', 'Close', 'Volume', 'RSI', 'MACD', 'BB_High', 'BB_Low']
    X = df[features]
    y = df['Target']

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    return train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

def train_and_evaluate(X_train, X_test, y_train, y_test):
    models = {
        'Logistic Regression': LogisticRegression(max_iter=1000),
        'Random Forest': RandomForestClassifier(),
        'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'LightGBM': LGBMClassifier()
    }

    for name, model in models.items():
        print(f"\n🧠 Training: {name}")
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        print(f"✅ Accuracy: {accuracy_score(y_test, y_pred):.4f}")
        print("✅ Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
        print("✅ Classification Report:\n", classification_report(y_test, y_pred))


In [23]:
df = fetch_history_stock_data('RELIANCE')
df = clean_stock_data(df, ticker='RELIANCE')
df = add_tech_indicator(df)
df = add_target_label(df)
X_train, X_test, y_train, y_test = preprocess(df)
train_and_evaluate(X_train, X_test, y_train, y_test)


[*********************100%***********************]  1 of 1 completed

🧹 Cleaning stock data...

🧠 Training: Logistic Regression
✅ Accuracy: 0.4854
✅ Confusion Matrix:
 [[22 92]
 [31 94]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.42      0.19      0.26       114
           1       0.51      0.75      0.60       125

    accuracy                           0.49       239
   macro avg       0.46      0.47      0.43       239
weighted avg       0.46      0.49      0.44       239


🧠 Training: Random Forest


✅ Accuracy: 0.4937
✅ Confusion Matrix:
 [[49 65]
 [56 69]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.47      0.43      0.45       114
           1       0.51      0.55      0.53       125

    accuracy                           0.49       239
   macro avg       0.49      0.49      0.49       239
weighted avg       0.49      0.49      0.49       239


🧠 Training: XGBoost
✅ Accuracy: 0.4812
✅ Confusion Matrix:
 [[49 65]
 [59 66]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.45      0.43      0.44       114
           1       0.50      0.53      0.52       125

    accuracy                           0.48       239
   macro avg       0.48      0.48      0.48       239
weighted avg       0.48      0.48      0.48       239


🧠 Training: LightGBM
[LightGBM] [Info] Number of positive: 499, number of negative: 454
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the over

In [24]:
# Handle class imbalance
X_train_sm, y_train_sm = SMOTE(random_state=42).fit_resample(X_train, y_train)

# Train and evaluate
train_and_evaluate(X_train_sm, X_test, y_train_sm, y_test)


🧠 Training: Logistic Regression
✅ Accuracy: 0.4603
✅ Confusion Matrix:
 [[52 62]
 [67 58]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.46      0.45       114
           1       0.48      0.46      0.47       125

    accuracy                           0.46       239
   macro avg       0.46      0.46      0.46       239
weighted avg       0.46      0.46      0.46       239


🧠 Training: Random Forest
✅ Accuracy: 0.5105
✅ Confusion Matrix:
 [[58 56]
 [61 64]]
✅ Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.51      0.50       114
           1       0.53      0.51      0.52       125

    accuracy                           0.51       239
   macro avg       0.51      0.51      0.51       239
weighted avg       0.51      0.51      0.51       239


🧠 Training: XGBoost
✅ Accuracy: 0.4979
✅ Confusion Matrix:
 [[55 59]
 [61 64]]
✅ Classification Report:
           